//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tekt.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\v11.0;Initial Catalog=C:\\USERS\\THEZER0IST\\TETKSYS\\TETKSYS\\T" +
            "EKT.WEB\\APP_DATA\\TEKTDEVDB.MDF;Integrated Security=True")]
        public string C__USERS_THEZER0IST_TETKSYS_TETKSYS_TEKT_WEB_APP_DATA_TEKTDEVDB_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_THEZER0IST_TETKSYS_TETKSYS_TEKT_WEB_APP_DATA_TEKTDEVDB_MDFConnectionStri" +
                    "ng"]));
            }
        }
    }
}
